#!/usr/bin/env bash

# Get the location for this script; handles symlinks
function get_script_path {
  local source="${BASH_SOURCE[0]}"
  while [ -h "$source" ] ; do
    local linked="$(readlink "$source")"
    local dir="$(cd -P $(dirname "$source") && cd -P $(dirname "$linked") && pwd)"
    source="$dir/$(basename "$linked")"
  done
  echo ${source}
}

# script details
declare -r script_path=$(get_script_path)
declare -r script_name=$(basename "$script_path")
declare -r script_dir="$(cd -P "$(dirname "$script_path")" && pwd)"

# directories
declare -r base_dir="$(cd "$script_dir/.." && pwd)"
declare -r lib_dir="$base_dir/lib"

# take the parameters
. $base_dir/bin/inc.env.sh

declare -r WLEARN_JAVA_OPTS=$VM_ARGS" -XX:+AggressiveOpts"
declare -r WLEARN_CLASSPATH=$PRJ_COMMONS_CLASSPATH

os_name=`uname`
architecture=`uname -m`
if [[ "$os_name" == 'Linux' ]]; then
   export LD_LIBRARY_PATH="$lib_dir/native/linux/$architecture/":$LD_LIBRARY_PATH
elif [[ "$os_name" == 'Darwin' ]]; then
   export LD_LIBRARY_PATH="$lib_dir/native/darwin/$architecture/":$LD_LIBRARY_PATH
else
    echo "[ ERROR ] Unsupported OS for native dependencies: MAP inference with Integer Linear Programming is not supported in this OS."
fi

nice java $WLEARN_JAVA_OPTS -cp $WLEARN_CLASSPATH lomrf.app.WeightLearningCLI $@
